### ISSUE TITLE
Select author

### ISSUE THREAD

**Issue by redlaguna** [nadilhassan/newsmodule#13]
Hello,

I can not assign an author. I'm trying the humhub version 1.2 beta 4. Which version should work properly?

**Comment by 001101** [comment]
https://en.wikipedia.org/wiki/Five_Ws

**Comment by redlaguna** [comment]
Hi 001101

I tried it in Google Chrome Versión 56.0.2924.87 the error in the console is as follows:

Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.success (userpicker.js?v=1490745603:278)
    at j (all-b70cdb3….js?v=1490745597:29)
    at Object.fireWith [as resolveWith] (all-b70cdb3….js?v=1490745597:29)
    at d (all-b70cdb3….js?v=1490745597:30)
    at XMLHttpRequest.<anonymous> (all-b70cdb3….js?v=1490745597:31)
(anonymous) @ userpicker.js?v=1490745603:278
j @ all-b70cdb3….js?v=1490745597:29
fireWith @ all-b70cdb3….js?v=1490745597:29
d @ all-b70cdb3….js?v=1490745597:30
(anonymous) @ all-b70cdb3….js?v=1490745597:31


The loggin of Humhub 1.2.0-beta.4 has the follow error:


ERROR  Mon, 03 Apr 2017 16:16:18 -0400  yii\base\ErrorException:8
exception 'yii\base\ErrorException' with message 'Undefined variable: imageGuid' in /home/mozmthlb/public_html/veci.mx/protected/modules/news/controllers/NewsController.php:91 Stack trace: #0 /home/mozmthlb/public_html/veci.mx/protected/modules/news/controllers/NewsController.php(91): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/home/mozmthlb/...', 91, Array) #1 [internal function]: humhub\modules\news\controllers\NewsController->actionCreate() #2 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #3 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) #4 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('create', Array) #5 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('news/news/creat...', Array) #6 /home/mozmthlb/public_html/veci.mx/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #7 /home/mozmthlb/public_html/veci.mx/index.php(25): yii\base\Application->run() #8 {main}

Thanks

Martin

**Comment by nadilhassan** [comment]
HI

I hope you can select an author from the suggestion list  but unfortunately the module core function is removed in 1.2 beta 4.. we are having discussion regarding that ..I will update this issue when it is sorted out

**Comment by redlaguna** [comment]
HI @nadilhassan 

Thank you for your time, I will be aware of the situation.

**Comment by Felli** [comment]
Here is the new [UserPicker.php](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/admin/views/group/edit.php#L30) in use. This information was provided by @buddh4

**Comment by Felli** [comment]
Need to implement `use humhub\modules\user\widgets\UserPickerField;`into the module. :+1:

**Comment by Felli** [comment]
@nadilhassan The issue was that in `views/news/edit.php` (call wasn't needed here) & `widgets/views/form.php` (Is needed here) existed a call to `humhub\modules\user\widgets\UserPicker::widget`, which both calls canceled one another out. I've also updated `models/EditForm.php` as well to fix this any other issues that should popup for this.
![](https://image.prntscr.com/image/KVSulUgoQPaZtKvkXuDs4g.png)

![](https://image.prntscr.com/image/TQRX5c2kQK21SDnY3P8Zwg.png).
