### ISSUE TITLE
Edit function failure

### ISSUE THREAD

**Issue by Cynicroute** [nadilhassan/newsmodule#17]
Articles are not able to be edited in HH 1.2.0. Edit function generates error:

```
An unexpected server error occured. If this keeps happening, please contact a site administrator.

{
    "url": "/index.php?r=news%2Fnews%2Fedit&id=6&sguid=30c71df5-b850-44f0-b5f1-b8fe5e369cbf",
    "status": 500,
    "response": "<pre>Exception &#039;yii\\base\\UnknownMethodException&#039; with message &#039;Calling unknown method: yii\\bootstrap\\ActiveForm::label()&#039; \n\nin /apps/humhub/protected/vendor/yiisoft/yii2/base/Component.php:290\n\nStack trace:\n#0 /apps/humhub/protected/modules/news/views/news/edit.php(23): yii\\base\\Component-&gt;__call(&#039;label&#039;, Array)\n#1 /apps/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require(&#039;/apps/humhub/pr...&#039;)\n#2 /apps/humhub/protected/vendor/yiisoft/yii2/b...",
    "textStatus": "error",
    "dataType": "html",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception &#039;yii\\base\\UnknownMethodException&#039; with message &#039;Calling unknown method: yii\\bootstrap\\ActiveForm::label()&#039; \n\nin /apps/humhub/protected/vendor/yiisoft/yii2/base/Component.php:290\n\nStack trace:\n#0 /apps/humhub/protected/modules/news/views/news/edit.php(23): yii\\base\\Component-&gt;__call(&#039;label&#039;, Array)\n#1 /apps/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require(&#039;/apps/humhub/pr...&#039;)\n#2 /apps/humhub/protected/vendor/yiisoft/yii2/base/View.php(250): yii\\base\\View-&gt;renderPhpFile(&#039;/apps/humhub/pr...&#039;, Array)\n#3 /apps/humhub/protected/humhub/components/View.php(112): yii\\base\\View-&gt;renderFile(&#039;/apps/humhub/pr...&#039;, Array, Object(humhub\\modules\\news\\controllers\\NewsController))\n#4 /apps/humhub/protected/vendor/yiisoft/yii2/web/Controller.php(49): humhub\\components\\View-&gt;renderAjax(&#039;edit&#039;, Array, Object(humhub\\modules\\news\\controllers\\NewsController))\n#5 /apps/humhub/protected/modules/news/controllers/NewsController.php(190): yii\\web\\Controller-&gt;renderAjax(&#039;edit&#039;, Array)\n#6 [internal function]: humhub\\modules\\news\\controllers\\NewsController-&gt;actionEdit()\n#7 /apps/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#8 /apps/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#9 /apps/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller-&gt;runAction(&#039;edit&#039;, Array)\n#10 /apps/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module-&gt;runAction(&#039;news/news/edit&#039;, Array)\n#11 /apps/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#12 /apps/humhub/index.php(25): yii\\base\\Application-&gt;run()\n#13 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "html": "<pre>Exception &#039;yii\\base\\UnknownMethodException&#039; with message &#039;Calling unknown method: yii\\bootstrap\\ActiveForm::label()&#039; \n\nin /apps/humhub/protected/vendor/yiisoft/yii2/base/Component.php:290\n\nStack trace:\n#0 /apps/humhub/protected/modules/news/views/news/edit.php(23): yii\\base\\Component-&gt;__call(&#039;label&#039;, Array)\n#1 /apps/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require(&#039;/apps/humhub/pr...&#039;)\n#2 /apps/humhub/protected/vendor/yiisoft/yii2/b...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}
```

**Comment by Felli** [comment]
I still haven't found a fix for this issue, could you provide a full error stack?

**Comment by Cynicroute** [comment]
Finally getting back to this...

```
yii\base\UnknownMethodException: Calling unknown method: yii\bootstrap\ActiveForm::label() in /apps/humhub/protected/vendor/yiisoft/yii2/base/Component.php:290 

Stack trace: 
#0 /apps/humhub/protected/modules/news/views/news/edit.php(23): yii\base\Component->__call('label', Array) 
#1 /apps/humhub/protected/vendor/yiisoft/yii2/base/View.php(328): require('/apps/humhub/pr...') 
#2 /apps/humhub/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/apps/humhub/pr...', Array) 
#3 /apps/humhub/protected/humhub/components/View.php(112): yii\base\View->renderFile('/apps/humhub/pr...', Array, Object(humhub\modules\news\controllers\NewsController)) 
#4 /apps/humhub/protected/vendor/yiisoft/yii2/web/Controller.php(49): humhub\components\View->renderAjax('edit', Array, Object(humhub\modules\news\controllers\NewsController)) 
#5 /apps/humhub/protected/modules/news/controllers/NewsController.php(190): yii\web\Controller->renderAjax('edit', Array) 
#6 [internal function]: humhub\modules\news\controllers\NewsController->actionEdit() 
#7 /apps/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#8 /apps/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array) 
#9 /apps/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('edit', Array) 
#10 /apps/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('news/news/edit', Array) 
#11 /apps/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
#12 /apps/humhub/index.php(25): yii\base\Application->run() 
#13 {main} 
```

**Comment by Cynicroute** [comment]
Migrating to HH1.3.8 on a new server and coming across this. Still not able to edit articles, but can post fine.

```
yii\base\UnknownMethodException: Calling unknown method: yii\bootstrap\ActiveForm::label() in /home/my/domain//protected/vendor/yiisoft/yii2/base/Component.php:300 Stack trace: 
#0 /home/my/domain//protected/modules/news/views/news/edit.php(20): yii\base\Component->__call('label', Array) 
#1 /home/my/domain//protected/vendor/yiisoft/yii2/base/View.php(336): require('/home/injurypr/...') 
#2 /home/my/domain//protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/injurypr/...', Array) 
#3 /home/my/domain//protected/humhub/modules/ui/view/components/View.php(111): yii\base\View->renderFile('/home/injurypr/...', Array, Object(humhub\modules\news\controllers\NewsController)) 
#4 /home/my/domain//protected/vendor/yiisoft/yii2/web/Controller.php(49): humhub\modules\ui\view\components\View->renderAjax('edit', Array, Object(humhub\modules\news\controllers\NewsController)) 
#5 /home/my/domain//protected/modules/news/controllers/NewsController.php(195): yii\web\Controller->renderAjax('edit', Array) 
#6 [internal function]: humhub\modules\news\controllers\NewsController->actionEdit() 
#7 /home/my/domain//protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#8 /home/my/domain//protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) 
#9 /home/my/domain//protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('edit', Array) 
#10 /home/my/domain//protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('news/news/edit', Array) 
#11 /home/my/domain//protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) 
#12 /home/my/domain//index.php(25): yii\base\Application->run() 
#13 {main} 
```
